var businessNames = `
TechNest;
CodeCraftHub;
EduTechPinnacle;
QuantumSphere;
InnovateSoft;
KnowledgePulse;
SoftwareVista;
TechStrive;
EduSyncSolutions;
QuantumQuestHub;
ByteBoostTech;
SmartMindScape;
LogicLoom;
InnovateIQ;
NexusEdTech;
CodeWaveSolutions;
TechMindsHub;
ByteBrilliance;
PinnacleTechPath;
QuantumLeapEdu;
InsightInnovate;
EduSyncSpectrum;
TechSavvySphere;
CodeCraftVortex;
EduInnovatePulse;
QuantumQuotient;
LogicLoomSolutions;
ByteBoostHub;
EduTechElevate;
PinnacleCodeCraft;
InnovateMindSync;
QuantumSphereTech;
TechWiseWave;
EduSavvySolutions;
ByteLogicLoom;
CodeCraftPulse;
QuantumEduInnovate;
PinnacleTechSync;
EduTechIQ;
InnovateCodeHub;
TechMindScape;
ByteInnovateTech;
LogicLoomEdu;
QuantumCraftHub;
EduSphereTech;
CodeSyncSolutions;
TechPinnacleIQ;
ByteElevateHub;
InnovateSmartMind;
QuantumEdTechPulse;
PinnacleTechBrilliance;
EduTechLeap;
CodeCraftQuotient;
TechNexusHub;
ByteLogicSphere;
InnovateEduScape;
QuantumMindSync;
EduWiseCraft;
PinnacleTechQuotient;
CodeSphereTech;
TechEduPulse;
ByteInnovateSync;
QuantumCodeHub;
EduCraftIQ;
PinnacleTechVortex;
InnovateMindScape;
CodeTechLeap;
ByteLogicCraft;
EduSyncSphere;
QuantumElevateTech;
TechQuotientHub;
PinnacleEdTechPulse;
InnovateCodeCraft;
ByteSphereTech;
LogicEduScape;
EduCraftQuotient;
QuantumTechLeap;
PinnacleEduHub;
CodeMindSync;
ByteTechSavvy;
InnovateEduSync;
QuantumCodePulse;
TechLogicLoom;
PinnacleMindScape;
EduSavvyCraft;
CodeCraftLeap;
ByteEdTechQuotient;
InnovateTechVortex;
QuantumSyncSolutions;
PinnacleCodeSphere;
EduMindSync;
TechCraftQuotient;
ByteEduLeap;
LogicTechSavvy;
InnovateMindSpectrum;
QuantumEduQuotient;
PinnacleSyncHub;
CodeTechLeap;
ByteMindSync
`;

function GeneratebusinessNames() {
    let item = businessNames.split(';\n');
    let rn = Math.floor(Math.random() * item.length);
    document.getElementById('businessNames').innerHTML = item[rn];
}

const businessSlogans = `
Nesting Innovation, Building Tomorrow;
Crafting Success with Code;
Pinnacle of Educational Technology;
Sphere of Quantum Possibilities;
Soft Solutions, Innovative Futures;
Pulsating Knowledge, Unleashing Potential;
Vista to Your Digital Future;
Strive for Excellence in Technology;
Syncing Minds, Transforming Education;
Hub of Quantum Learning Journeys;
Boosting Bytes, Empowering Tech;
Smart Minds in a Creative Landscape;
Weave Logic, Shape Solutions;
IQ of Innovation, Wisdom of Progress;
Nexus of Educational Technologies;
Riding the Wave of Code Solutions;
Hub of Tech Minds, Unleashing Ideas;
Brilliance in Every Byte;
Pinnacle on the Path of Tech Excellence;
Quantum Leap in Education;
Innovate with Insightful Solutions;
Spectrum of Synced Education;
Navigating the Savvy Sphere of Tech;
Crafting Success in the Vortex of Code;
Pulsating Innovation in Education;
Quotient of Quantum Excellence;
Solutions Woven with Logical Precision;
Hub of Byte-Boosted Innovations;
Elevating Education through Tech;
Code Crafted to Pinnacle Perfection;
Syncing Minds for Innovative Solutions;
Tech Transformations in Quantum Sphere;
Riding the Wise Wave of Tech;
Savvy Solutions for Education;
Logic Woven into Every Byte;
Pulse of Code, Rhythm of Success;
Innovating Education with Quantum;
Synced to Pinnacle Tech;
IQ Infused in Educational Tech;
Hub of Innovative Code Solutions;
Minds Exploring the Techscape;
Innovating Tech Byte by Byte;
Educational Solutions with Logical Precision;
Crafting the Quantum Future;
Tech Explorations in the Educational Sphere;
Synced Solutions in the Code Realm;
Pinnacle IQ in Technology;
Elevating Innovations Byte by Byte;
Smart Minds, Innovative Solutions;
Pulsating EdTech Innovations;
Brilliance at the Pinnacle of Tech;
Leaping into the Future of Education;
Crafting Success Quotient in Code;
Hub of Tech Nexus, Connecting Innovations;
Logic in Every Sphere of Byte;
Sculpting Educational Landscapes of Innovation;
Syncing Minds with Quantum Insights;
Wise Crafting in Education;
Quotient of Pinnacle Tech Excellence;
Tech Transformations in Code Sphere;
Pulse of Tech in Education;
Syncing Innovations Byte by Byte;
Hub of Quantum Code Solutions;
Crafting IQ through Education;
Vortex of Tech Excellence at Pinnacle;
Sculpting Innovative Mindscape;
Leaping into the Future with Code;
Crafting Logic Byte by Byte;
Sphere of Synced Education;
Elevating Tech with Quantum Innovations;
Hub of Tech Quotient Excellence;
Pulsating EdTech at the Pinnacle;
Crafting Innovative Code Solutions;
Tech Transformations in Byte Sphere;
Educational Landscapes with Logical Precision;
Quotient of Craft in Education;
Quantum Leap into the Future of Tech;
Hub of Educational Pinnacle;
Syncing Minds through Code;
Tech Savvy Byte by Byte;
Syncing Innovation with Education;
Pulse of Quantum Code Innovations;
Weaving Logic in the Tech Loom;
Sculpting Mindscape at the Pinnacle;
Crafting Savvy Solutions in Education;
Leaping into Success with Code Craft;
Quotient of EdTech in Every Byte;
Vortex of Innovative Tech Solutions;
Syncing Solutions with Quantum Precision;
Code Transformations at the Pinnacle;
Syncing Minds in Education;
Quotient of Crafting Tech Excellence;
Leaping into Educational Excellence Byte by Byte;
Tech Savvy Logic in Every Solution;
Spectrum of Innovative Minds;
Quotient of Educational Quantum;
Sync Hub at the Pinnacle;
Leaping into the Future with Code;
Syncing Minds Byte by Byte;
Exploring the Educational Tech Sphere;
`;

function GeneratebusinessSlogans() {
    let item = businessSlogans.split(';\n');
    let rn = Math.floor(Math.random() * item.length);
    document.getElementById('businessSlogans').innerHTML = item[rn];
}
const captions = `
    Building tomorrow with innovative nests of ideas;
    Crafting success through the language of code;
    Reaching the pinnacle of educational technology;
    Exploring a sphere filled with quantum possibilities;
    Creating innovative futures with soft solutions;
    Unleashing the potential of knowledge with pulsating energy;
    Vista to your digital future, where success awaits;
    Striving for excellence in the vast landscape of technology;
    Transforming education by syncing minds;
    Embarking on quantum learning journeys as a hub of knowledge;
    Empowering tech by boosting bytes;
    Navigating a creative landscape with smart minds;
    Shaping solutions by weaving logic into the code;
    Progressing with the IQ of innovation and wisdom;
    Connecting the nexus of educational technologies;
    Riding the wave of solutions with code;
    Unleashing ideas as a hub of tech minds;
    Infusing brilliance into every byte;
    Walking the path of tech excellence at the pinnacle;
    Taking a quantum leap forward in education;
    Innovating with insightful solutions;
    Creating a spectrum of synced education;
    Navigating the savvy sphere of tech;
    Crafting success in the vortex of code;
    Pulsating innovation in the landscape of education;
    Achieving a quotient of quantum excellence;
    Precision in solutions woven with logical brilliance;
    Being a hub of byte-boosted innovations;
    Elevating education through meticulously crafted tech;
    Crafting code to pinnacle perfection;
    Syncing minds for innovative solutions;
    Witnessing tech transformations in the quantum sphere;
    Riding the wise wave of technology;
    Providing savvy solutions for education;
    Weaving logic into every byte of innovation;
    Feeling the pulse of code, the rhythm of success;
    Innovating education with a quantum mindset;
    Experiencing code transformations at the pinnacle;
    Syncing minds in the field of education;
    Achieving the quotient of crafting tech excellence;
    Leaping into educational excellence byte by byte;
    Applying tech-savvy logic in every solution;
    Exploring a spectrum of innovative minds;
    Experiencing the quotient of educational quantum;
    Syncing the hub at the pinnacle;
    Leaping into the future with the language of code;
    Syncing minds byte by byte;
    Exploring the educational tech sphere;
  `;

function Generatecaptions() {
    let item = captions.split(';\n');
    let rn = Math.floor(Math.random() * item.length);
    document.getElementById('captions').innerHTML = item[rn];
}
const jokes = `
    Why did the innovative nests of ideas go to therapy? They needed to rebuild their relationship;
    How does success communicate? Through the language of code, of course - it's binary brilliant;
    Why did the educational technology bring a ladder? To reach the pinnacle of knowledge, step by step;
    Why did the quantum possibilities throw a party? Because exploring a sphere is always a celebration;
    How does soft solutions create innovative futures? By knitting success with a magical touch;
    Why did the potential of knowledge start a band? Because it wanted to unleash its pulsating energy;
    What did the digital future say to success? "Vista to your destiny, where achievement awaits;"
    How does technology strive for excellence? By navigating the vast landscape with a virtual compass;
    Why did education sync minds? To transform minds into a harmonious symphony of wisdom;
    How did the hub of knowledge become quantum? By embarking on learning journeys faster than light;
    Why did tech boost bytes? To empower itself with a digital energy drink;
    What did the creative landscape say to smart minds? "Navigate me, and let's create wonders together;"
    How does logic weave into the code? By shaping solutions with a loom of brilliance;
    Why did innovation and wisdom form a superhero duo? Because they progress with the IQ of superheroes;
    How did educational technologies connect? By creating a nexus where ideas meet and mingle;
    Why did the wave ride solutions with code? Because riding solo is too mainstream for success;
    How did the hub of tech minds unleash ideas? By turning them into a digital hurricane;
    Why did brilliance infuse into every byte? It wanted to light up the world with knowledge;
    What did the path of tech excellence say? "Walk with me, and we'll reach the pinnacle together;"
    Why did education take a quantum leap? Because regular leaps are so last season;
    How do insightful solutions innovate? By having light bulb moments in the dark;
    What did synced education create? A beautiful spectrum where minds dance in harmony;
    Why did the savvy sphere of tech never get lost? It had a built-in GPS for success;
    How did success craft in the vortex of code? By swirling creativity and logic into a perfect storm;
    Why did innovation pulsate in the landscape of education? Because it had a heartbeat of progress;
    How did quantum excellence achieve its quotient? By counting bits of success in binary;
    Why did logical brilliance weave into solutions? Because precision is the fabric of success;
    How did byte-boosted innovations form a supergroup? By being a hub where creativity rocked;
    Why did meticulously crafted tech elevate education? Because it believed in taking things to the next level;
    How did code reach pinnacle perfection? By climbing the ladder of 0s and 1s;
    Why did synced minds create innovative solutions? Because two brains are better than one;
    How did the tech sphere experience quantum transformations? By warping reality with the power of innovation;
    Why did the wise wave of technology become a mentor? To guide aspiring minds to success;
    How did savvy solutions party in education? By throwing a celebration of knowledge;
    Why did logic weave into every byte of innovation? Because it believed in threading success;
    What did the pulse of code say to success? "Feel the rhythm, ride the wave, and dance to victory;"
    How did a quantum mindset innovate education? By thinking in dimensions beyond the ordinary;
    Why did code transformations party at the pinnacle? Because success knows how to celebrate;
    How did synced minds leap into educational excellence? By jumping byte by byte to achievement;
    Why did crafting tech excellence have a tech-savvy logic? Because logic is the key to unlocking success;
    How did educational excellence leap into the future? Byte by byte, one quantum leap at a time;
    Why did tech-savvy logic party in every solution? Because it knew how to algorithmically groove;
    What did innovative minds explore? A spectrum of possibilities where creativity knows no bounds;
    How did educational quantum sync at the pinnacle? By aligning the stars of knowledge and brilliance;
    Why did the future sync with the language of code? Because it wanted to speak the language of success;
    How did minds sync byte by byte? By dancing to the rhythm of innovation;
    What did the educational tech sphere explore? A galaxy of possibilities where learning is infinite;
`;

function Generatejokes() {
    let item = jokes.split(';\n');
    let rn = Math.floor(Math.random() * item.length);
    document.getElementById('jokes').innerHTML = item[rn];
}